development:
  adapter: postgresql
  encoding: unicode
  database: knoiz_development
  pool: 5
  username: hugo
  password: root
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: knoiz_test
  pool: 5
  username: hugo
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: knoiz_db
  pool: 5
  username: knoiz
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host: localhost
  port: 5432
