development:
  adapter: postgresql
  encoding: unicode
  database: djai_development
  pool: 5
  username: <%= ENV['POSTGRESQL_USER'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: djai_test
  pool: 5
  username: <%= ENV['POSTGRESQL_USER'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: djai_production
  pool: 5
  username: <%= ENV['POSTGRESQL_USER'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>