development:
  adapter: postgresql
  encoding: unicode
  database: djai_development
  pool: 5
  username: djai
  password: djai
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: djai_test
  pool: 5
  username: djai
  password: djai

production:
  adapter: postgresql
  encoding: unicode
  database: djai_production
  pool: 5
  username: djai
  password: djai